import { useState } from 'react'
import { api } from '../lib/api'

const SECTION_TITLES = [
  'SECTION 1 — PATIENT OVERVIEW',
  'SECTION 2 — SYMPTOM TIMELINE AND PATTERNS',
  'SECTION 3 — ROTTERDAM CRITERIA ASSESSMENT',
  'SECTION 4 — PASSIVE HEALTH DATA ANALYSIS',
  'SECTION 5 — CLINICAL RECOMMENDATIONS',
]

function parseSections(text) {
  if (!text) return []
  const sections = []
  let remaining = text
  for (let i = 0; i < SECTION_TITLES.length; i++) {
    const thisTitle = SECTION_TITLES[i]
    const nextTitle = SECTION_TITLES[i + 1]
    const startIdx = remaining.indexOf(thisTitle)
    if (startIdx === -1) continue
    const bodyStart = startIdx + thisTitle.length
    const endIdx = nextTitle ? remaining.indexOf(nextTitle, bodyStart) : remaining.length
    const body = remaining.slice(bodyStart, endIdx !== -1 ? endIdx : undefined).trim()
    sections.push({ title: thisTitle, body })
  }
  return sections
}

export default function Report({ showToast }) {
  const [loading, setLoading] = useState(false)
  const [report, setReport] = useState('')
  const [copied, setCopied] = useState(false)

  const savedSymptoms = (() => {
    try { return JSON.parse(localStorage.getItem('clover_symptoms') || '[]') } catch { return [] }
  })()
  const savedAnything = localStorage.getItem('clover_anything_else') || ''
  const savedCriteria = (() => {
    try { return JSON.parse(localStorage.getItem('clover_criteria_state') || '{}') } catch { return {} }
  })()

  async function generateReport() {
    if (savedSymptoms.length === 0) {
      showToast('Please build your symptom case first on the Symptoms tab', 'error')
      return
    }
    setLoading(true)
    setReport('')
    try {
      const data = await api.report(savedSymptoms, savedAnything, '', savedCriteria)
      setReport(data.report)
    } catch (e) {
      showToast(e.message || 'Report generation failed', 'error')
    } finally {
      setLoading(false)
    }
  }

  async function copyReport() {
    try {
      await navigator.clipboard.writeText(report)
      setCopied(true)
      showToast('Report copied to clipboard', 'success')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      showToast('Could not copy — please select and copy manually', 'error')
    }
  }

  function printReport() {
    const win = window.open('', '_blank')
    win.document.write(`
      <html><head><title>Clover PCOS Report</title>
      <style>
        body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #1C1730; line-height: 1.8; font-size: 15px; }
        h1 { font-size: 24px; margin-bottom: 8px; }
        .subtitle { color: #6B6080; margin-bottom: 32px; font-size: 13px; }
        .section-title { font-weight: bold; font-size: 12px; letter-spacing: 0.06em; text-transform: uppercase; border-left: 3px solid #6A4ED4; padding-left: 10px; margin: 28px 0 12px; color: #6A4ED4; }
        .section-body { white-space: pre-wrap; }
        .footer { margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
      </style></head><body>
      <h1>Clover PCOS Clinical Report</h1>
      <div class="subtitle">Generated ${new Date().toLocaleDateString()} · For clinical discussion with your GP</div>
      ${parseSections(report).map(s => `
        <div class="section-title">${s.title}</div>
        <div class="section-body">${s.body}</div>
      `).join('')}
      <div class="footer">This report was generated by Clover and does not constitute a medical diagnosis. It is intended solely to support clinical discussion with a qualified healthcare provider.</div>
      </body></html>
    `)
    win.document.close()
    win.print()
  }

  const sections = parseSections(report)

  return (
    <div>
      <h1 className="page-title">Clinical Report</h1>
      <p className="page-subtitle">A structured, evidence-based symptom report formatted for your GP.</p>

      {savedSymptoms.length > 0 ? (
        <div className="card" style={{ marginBottom: 20 }}>
          <div className="section-label">Symptoms on record</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 8 }}>
            {savedSymptoms.map(s => (
              <span key={s} style={{ padding: '4px 12px', borderRadius: 99, background: 'var(--lav-light)', color: 'var(--lav-deep)', fontSize: 12, fontWeight: 600 }}>
                {s}
              </span>
            ))}
          </div>
        </div>
      ) : (
        <div className="card" style={{ marginBottom: 20 }}>
          <div className="empty-state">
            <div className="empty-state-title">No symptoms saved yet</div>
            <div className="empty-state-desc">Go to the Symptoms tab, build your case, then come back here to generate your report.</div>
          </div>
        </div>
      )}

      <div className="report-actions">
        <button
          className="btn btn-primary"
          onClick={generateReport}
          disabled={loading || savedSymptoms.length === 0}
        >
          {loading ? <><span className="spinner" /> Generating report…</> : 'Generate Report'}
        </button>

        {report && (
          <>
            <button className="btn btn-ghost" onClick={copyReport}>
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <button className="btn btn-ghost" onClick={printReport}>
              Print / Save PDF
            </button>
          </>
        )}
      </div>

      {loading && (
        <div className="loading-box">
          <span className="spinner dark" style={{ width: 28, height: 28, borderWidth: 3 }} />
          <div>
            <div style={{ fontWeight: 700, marginBottom: 4 }}>Generating your clinical report…</div>
            <div style={{ fontSize: 13 }}>This typically takes 10–20 seconds. Claude is writing a detailed 5-section document.</div>
          </div>
        </div>
      )}

      {sections.length > 0 && (
        <div className="card">
          {sections.map((s, i) => (
            <div key={i} className="report-section">
              <div className="report-section-title">{s.title}</div>
              <div className="report-body">{s.body}</div>
              {i < sections.length - 1 && <div className="divider" style={{ marginTop: 20 }} />}
            </div>
          ))}
        </div>
      )}

      {report && sections.length === 0 && (
        <div className="card">
          <div className="report-body">{report}</div>
        </div>
      )}
    </div>
  )
}
